x-image: &image
  ghcr.io/onedr0p/exportarr:latest

x-shared: &shared
  extends:
    file: ./shared.yaml
    service: shared-syslog

services:
  sonarr-exporter:
    <<: *shared
    image: *image
    command: ["sonarr"]
    environment:
      URL: ${SONARR_URL}
      APIKEY: ${SONARR_TOKEN}
    restart: unless-stopped

  radarr-exporter:
    <<: *shared
    image: *image
    command: ["radarr"]
    environment:
      URL: ${RADARR_URL}
      APIKEY: ${RADARR_TOKEN}
    restart: unless-stopped

  prowlarr-exporter:
    <<: *shared
    image: *image
    command: ["prowlarr"]
    environment:
      URL: ${PROWLARR_URL}
      APIKEY: ${PROWLARR_TOKEN}
    restart: unless-stopped

  node-exporter:
    <<: *shared
    image: prom/node-exporter:latest
    command:
      - "--path.rootfs=/host"
    volumes:
      - "/:/host:ro,rslave"