x-shared: &shared
  extends:
    file: ./shared.yaml
    service: shared-syslog

services:
  traefik:
    <<: *shared
    image: traefik:v2.11
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    configs:
      - source: traefik_config
        target: /etc/traefik/traefik.yml
      - source: traefik_mw
        target: /etc/traefik/traefik-mw.yml
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - "${VOL_ROOT}/traefik/acme:/etc/acme"
  organizr:
    <<: *shared
    environment:
      - fpm=true
      - branch=v2-master # or v2-develop
    image: docker.io/organizr/organizr:latest
    volumes:
      - "${VOL_ROOT}/organizr:/config"
    labels:
      - traefik.enable=true
      - traefik.http.routers.organizr.rule=Host(`${DOMAIN}`)
      - traefik.http.routers.organizr.tls=true
      - traefik.http.routers.organizr.tls.certresolver=myresolver
  plex:
    <<: *shared
    image: lscr.io/linuxserver/plex:latest
    environment:
      - VERSION=docker
      #- PLEX_CLAIM=xxx
    volumes:
      - "${VOL_ROOT}/plex:/config"
      - "${VOL_MEDIA}:/media"
    ports:
      - 32400:32400
      - 1900:1900/udp
      - 3005:3005
      - 5353:5353/udp
      - 8324:8324
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
      - 32469:32469
    labels:
      - traefik.enable=true
      - traefik.http.routers.plex.tls=true
      - traefik.http.routers.plex.tls.certresolver=myresolver
      - traefik.http.services.plex.loadbalancer.server.port=32400

  jellyfin:
    <<: *shared
    image: linuxserver/jellyfin:latest
    volumes:
      - "${VOL_ROOT}/jellyfin:/config"
      - "${VOL_MEDIA}:/media"
    ports:
      - 8096:8096
      - 8020:8020
      - 7359:7359/udp
      #- 1900:1900/udp
    labels:
      - traefik.enable=true
      - traefik.http.routers.jellyfin.tls=true
      - traefik.http.routers.jellyfin.tls.certresolver=myresolver
      - traefik.http.services.jellyfin.loadbalancer.server.port=8096

  metatube:
    <<: *shared
    image: metatube/metatube-server:1.2.6
    command: -dsn /config/metatube.db -port 8080
    volumes:
      - "${VOL_ROOT}/metatube:/config"

  plexsync:
    <<: *shared
    image: eben0/plexsync:latest

  qb: # torrent client
    <<: *shared
    image: lscr.io/linuxserver/qbittorrent:latest
    environment:
      - WEBUI_PORT=8081
    volumes:
      - "${VOL_ROOT}/qbittorrent:/config"
      - "${VOL_MEDIA}:/media"
    ports:
      - 6881:6881
      - 6881:6881/udp
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.qb-redirect.redirectregex.regex=^(.*)/qb$$"
      - "traefik.http.middlewares.qb-redirect.redirectregex.replacement=$$1/qb/"
      - "traefik.http.middlewares.qb-strip.stripprefix.prefixes=/qb/"
      # appropropriate header changes
      - "traefik.http.middlewares.qb-headers.headers.customrequestheaders.X-Frame-Options=SAMEORIGIN"
      - "traefik.http.middlewares.qb-headers.headers.customrequestheaders.Referer="
      - "traefik.http.middlewares.qb-headers.headers.customrequestheaders.Origin="
      - "traefik.http.routers.qb.middlewares=qb-strip,qb-redirect,qb-headers,auth@file"
      # loadbalancer to *not* pass the host header
      - "traefik.http.services.qb.loadbalancer.server.port=8081"
      - "traefik.http.services.qb.loadbalancer.passhostheader=false"
      - traefik.http.routers.qb.tls=true
      - traefik.http.routers.qb.tls.certresolver=myresolver
  i2p:
    <<: *shared
    image: geti2p/i2p:latest
    volumes:
      - "./i2p/i2p-console.config:/i2p/.i2p/clients.config.d/00-console.config"
      - "${VOL_ROOT}/i2p/config:/i2p/.i2p"
      - "${VOL_ROOT}/i2p/torrents:/i2psnark"
    ports:
      - 6668:6668
      - 7657:7657
      - 54321:12345
      - 54321:12345/udp
  nzbget: # usenet client
    <<: *shared
    image: linuxserver/nzbget:latest
    volumes:
      - "${VOL_ROOT}/nzbget:/config"
      - "${VOL_MEDIA}:/media"
    labels:
      - traefik.enable=true
      - traefik.http.routers.nzbget.tls=true
      - traefik.http.routers.nzbget.tls.certresolver=myresolver
      - traefik.http.routers.nzbget.middlewares=auth@file
  # movie search
  radarr:
    <<: *shared
    image: linuxserver/radarr:latest
    ports:
      - 7878:7878
    volumes:
      - "${VOL_ROOT}/radarr:/config"
      - "${VOL_MEDIA}:/media"
    labels:
      - traefik.enable=true
      - traefik.http.routers.radarr.tls=true
      - traefik.http.routers.radarr.tls.certresolver=myresolver
      - traefik.http.routers.radarr.middlewares=auth@file

  sonarr:
    <<: *shared
    image: linuxserver/sonarr:latest
    ports:
      - 8989:8989
    volumes:
      - "${VOL_ROOT}/sonarr:/config"
      - "${VOL_MEDIA}:/media"
    labels:
      - traefik.enable=true
      - traefik.http.routers.sonarr.tls=true
      - traefik.http.routers.sonarr.tls.certresolver=myresolver
      - traefik.http.routers.sonarr.middlewares=auth@file

  bazarr:
    <<: *shared
    image: linuxserver/bazarr:latest
    volumes:
      - "${VOL_ROOT}/bazarr:/config"
      - "${VOL_MEDIA}:/media"
    labels:
      - traefik.enable=true
      - traefik.http.routers.bazarr.tls=true
      - traefik.http.routers.bazarr.tls.certresolver=myresolver
      - traefik.http.routers.bazarr.middlewares=auth@file

  prowlarr:
    <<: *shared
    image: linuxserver/prowlarr:latest
    volumes:
      - "${VOL_ROOT}/prowlarr:/config"
    labels:
      - traefik.enable=true
      - traefik.http.routers.prowlarr.tls=true
      - traefik.http.routers.prowlarr.tls.certresolver=myresolver
      - traefik.http.routers.prowlarr.middlewares=auth@file

  ombi:
    <<: *shared
    image: linuxserver/ombi:latest
    volumes:
      - "${VOL_ROOT}/ombi:/config"
    environment:
      BASE_URL: /ombi
    labels:
      - traefik.enable=true
      - traefik.http.routers.ombi.tls=true
      - traefik.http.routers.ombi.tls.certresolver=myresolver
      - traefik.http.routers.ombi.middlewares=auth@file

  tautulli:
    <<: *shared
    image: ghcr.io/tautulli/tautulli:latest
    volumes:
      - "${VOL_ROOT}/tautulli:/config"
    labels:
      - traefik.enable=true
      - traefik.http.routers.tautulli.tls=true
      - traefik.http.routers.tautulli.tls.certresolver=myresolver
      - traefik.http.routers.tautulli.middlewares=auth@file

  #db:
  #  <<: *shared
  #  image: postgres:15.4
  #  volumes:
  #    - db-storage:/var/lib/postgresql/data
  #  ports:
  #    - 5432:5432

  #pgadmin:
  #  <<: *shared
  #  image: dpage/pgadmin4
  #  volumes:
  #    - "${VOL_ROOT}/pgadmin:/var/lib/pgadmin:rw"
  #  ports:
  #    - 8888:80
  
  flaresolverr:
    <<: *shared
    image: ghcr.io/flaresolverr/flaresolverr:latest

  unpackerr:
    <<: *shared
    image: ghcr.io/unpackerr/unpackerr:latest
    volumes:
      - "${VOL_MEDIA}/downloads:/downloads"

  #ddclient:
  #  <<: *shared
  #  image: lscr.io/linuxserver/ddclient:latest
  #  volumes:
  #    - ./ddclient/ddclient.conf:/tmp/ddclient.conf
  #    - ./ddclient/env_config.sh:/custom-cont-init.d/env_config.sh:ro

configs:
  traefik_config:
    file: ./proxy/traefik.yml
  traefik_mw:
    file: ./proxy/traefik-mw.yml