x-shared: &shared
  env_file:
    - vars.env
  restart: unless-stopped
  logging:
    driver: loki
    options:
      loki-url: "http://localhost:3100/loki/api/v1/push"
      mode: non-blocking
      max-buffer-size: 4m
      loki-retries: "3"

services:
  plex:
    <<: *shared
    image: lscr.io/linuxserver/plex:latest
    environment:
      - VERSION=docker
      #- PLEX_CLAIM=claim-AgxRVcHN4CoKnxWhHpAT
    volumes:
      - "${VOL_ROOT}/plex:/config"
      - "${VOL_MEDIA}:/media"
      - "winshare:/winshare"
    ports:
      - 32400:32400
      - 1900:1900/udp
      - 3005:3005
      - 5353:5353/udp
      - 8324:8324
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
      - 32469:32469

  jellyfin:
    <<: *shared
    image: linuxserver/jellyfin:latest
    volumes:
      - "${VOL_ROOT}/jellyfin:/config"
      - "${VOL_MEDIA}:/media"
      - "winshare:/winshare"
    ports:
      - 8096:8096
      - 8020:8020
      - 7359:7359/udp
      #- 1900:1900/udp
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.jellyfin.loadbalancer.server.port=8096"

  plexsync:
    <<: *shared
    image: eben0/plexsync:latest

  qb: # torrent client
    <<: *shared
    image: lscr.io/linuxserver/qbittorrent:latest
    environment:
      - WEBUI_PORT=8081
    volumes:
      - "${VOL_ROOT}/qbittorrent:/config"
      - "${VOL_MEDIA}:/media"
      - "winshare:/winshare"
    ports:
      - 8081:8081
      - 6881:6881
      - 6881:6881/udp
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.qb.rule=PathPrefix(`/qb`)"
      - "traefik.http.middlewares.qb-redirect.redirectregex.regex=^(.*)/qb$$"
      - "traefik.http.middlewares.qb-redirect.redirectregex.replacement=$$1/qb/"
      - "traefik.http.middlewares.qb-strip.stripprefix.prefixes=/qb/"
      # appropropriate header changes
      - "traefik.http.middlewares.qb-headers.headers.customrequestheaders.X-Frame-Options=SAMEORIGIN"
      - "traefik.http.middlewares.qb-headers.headers.customrequestheaders.Referer="
      - "traefik.http.middlewares.qb-headers.headers.customrequestheaders.Origin="
      - "traefik.http.routers.qb.middlewares=qb-strip,qb-redirect,qb-headers"
      # loadbalancer to *not* pass the host header
      - "traefik.http.services.qb.loadbalancer.server.port=8081"
      - "traefik.http.services.qb.loadbalancer.passhostheader=false"

  nzbget: # usenet client
    <<: *shared
    image: linuxserver/nzbget:latest
    volumes:
      - "${VOL_ROOT}/nzbget:/config"
      - "${VOL_MEDIA}:/media"
      - "winshare:/winshare"
    ports:
      - 6789:6789
    labels:
      - "traefik.enable=true"

  # movie search
  radarr:
    <<: *shared
    image: linuxserver/radarr:latest
    volumes:
      - "${VOL_ROOT}/radarr:/config"
      - "${VOL_MEDIA}:/media"
      - "winshare:/winshare"
    ports:
      - 7878:7878
    labels:
      - "traefik.enable=true"

  sonarr:
    <<: *shared
    image: linuxserver/sonarr:latest
    volumes:
      - "${VOL_ROOT}/sonarr:/config"
      - "${VOL_MEDIA}:/media"
      - "winshare:/winshare"
    ports:
      - 8989:8989
    labels:
      - "traefik.enable=true"

  bazarr:
    <<: *shared
    image: linuxserver/bazarr:latest
    volumes:
      - "${VOL_ROOT}/bazarr:/config"
      - "${VOL_MEDIA}:/media"
      - "winshare:/winshare"
    ports:
      - 6767:6767
    labels:
      - "traefik.enable=true"

  prowlarr:
    <<: *shared
    image: linuxserver/prowlarr:latest
    volumes:
      - "${VOL_ROOT}/prowlarr:/config"
    ports:
      - 9696:9696
    labels:
      - "traefik.enable=true"

  ombi:
    <<: *shared
    image: linuxserver/ombi:latest
    volumes:
      - "${VOL_ROOT}/ombi:/config"
    ports:
      - 5000:3579
    environment:
      BASE_URL: /ombi
    labels:
      - "traefik.enable=true"

  tautulli:
    <<: *shared
    image: ghcr.io/tautulli/tautulli:latest
    volumes:
      - "${VOL_ROOT}/tautulli:/config"
    ports:
      - 8181:8181
    labels:
      - "traefik.enable=true"

  #db:
  #  <<: *shared
  #  image: postgres:15.4
  #  volumes:
  #    - db-storage:/var/lib/postgresql/data
  #  ports:
  #    - 5432:5432

  #pgadmin:
  #  <<: *shared
  #  image: dpage/pgadmin4
  #  volumes:
  #    - "${VOL_ROOT}/pgadmin:/var/lib/pgadmin:rw"
  #  ports:
  #    - 8888:80

  organizr:
    <<: *shared
    environment:
      - fpm=true
      - branch=v2-master # or v2-develop
    image: docker.io/organizr/organizr:latest
    volumes:
      - "${VOL_ROOT}/organizr:/config"
    ports:
      - 81:80
    labels:
      - "traefik.enable=true"
      - traefik.http.routers.organizr.rule=PathPrefix(`/`)
  
  flaresolverr:
    <<: *shared
    image: ghcr.io/flaresolverr/flaresolverr:latest

  reverse-proxy:
    <<: *shared
    image: traefik:v2.11
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - ./proxy/traefik.yml:/etc/traefik/traefik.yml
      - /var/run/docker.sock:/var/run/docker.sock

  ddclient:
    <<: *shared
    image: lscr.io/linuxserver/ddclient:latest
    volumes:
      - ./ddclient/ddclient.conf:/tmp/ddclient.conf
      - ./ddclient/env_config.sh:/custom-cont-init.d/env_config.sh:ro

volumes:
  db-storage:
  winshare:
    driver_opts:
      type: cifs
      o: "username=${HOST_USER},password=${HOST_PASS},uid=${PUID},gid=${PGID},vers=3.0,rw"
      device: "${VOL_WINSHARE}"