x-shared: &shared
  restart: unless-stopped
  extra_hosts:
    - host.docker.internal:host-gateway
  logging:
    driver: loki
    options:
      loki-url: "http://localhost:3100/loki/api/v1/push"
      mode: non-blocking
      max-buffer-size: 4m
      loki-retries: "3"

services:
  grafana:
    <<: *shared
    image: grafana/grafana
    environment:
      GF_SERVER_ROOT_URL: "%(protocol)s://%(domain)s:%(http_port)s/grafana"
      GF_SERVER_SERVE_FROM_SUB_PATH: true
    volumes:
      -  grafana-storage:/var/lib/grafana
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"

  prometheus:
    <<: *shared
    image: prom/prometheus
    command:
      - '--config.file=/etc/prometheus/config.yaml'
      - '--log.level=debug'
    volumes:
      - "./monitoring/prometheus.yaml:/etc/prometheus/config.yaml"
      - prom-storage:/prometheus
    depends_on:
      - cadvisor

  loki:
    <<: *shared
    image: grafana/loki:2.8.0
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - "./monitoring/loki.yaml:/etc/loki/config.yaml"
    restart: unless-stopped

  promtail:
    <<: *shared
    image: grafana/promtail:2.8.0
    command: -config.file=/etc/promtail/config.yml
    volumes:
      - /var/log:/var/log
      - "./monitoring/promtail.yaml:/etc/promtail/config.yml"
    restart: unless-stopped

  cadvisor:
    <<: *shared
    image: gcr.io/cadvisor/cadvisor:latest
    privileged: true
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro

  portainer:
    <<: *shared
    image: portainer/portainer-ce:latest
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - portainer-storage:/data
    #labels:
    #  - "traefik.enable=true"
    #  - "traefik.http.services.portainer.loadbalancer.server.port=9000"
    #  - "traefik.http.middlewares.portainer-strip.stripprefix.prefixes=/portainer"
    #  - "traefik.http.routers.portainer.middlewares=portainer-strip"

volumes:
  grafana-storage:
  prom-storage:
  portainer-storage:
  redis-storage:
