x-shared: &shared
  restart: unless-stopped
  extra_hosts:
    - host.docker.internal:host-gateway
  logging:
    driver: loki
    options:
      loki-url: "http://localhost:3100/loki/api/v1/push"

services:
  grafana:
    <<: *shared
    image: grafana/grafana
    ports:
      - 3000:3000
    volumes:
      -  grafana-storage:/var/lib/grafana

  prometheus:
    <<: *shared
    image: prom/prometheus
    command:
      - '--config.file=/etc/prometheus/config.yaml'
      - '--log.level=debug'
    volumes:
      - "${VOL_ROOT}/monitoring/prometheus.yaml:/etc/prometheus/config.yaml"
      - prom-storage:/prometheus
    depends_on:
      - cadvisor

  loki:
    <<: *shared
    image: grafana/loki:2.8.0
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - "${VOL_ROOT}/monitoring/loki.yaml:/etc/loki/config.yaml"
    ports:
      - 3100:3100
    restart: unless-stopped

  promtail:
    <<: *shared
    image: grafana/promtail:2.8.0
    command: -config.file=/etc/promtail/config.yml
    volumes:
      - /var/log:/var/log
      - "${VOL_ROOT}/monitoring/promtail.yaml:/etc/promtail/config.yml"
    restart: unless-stopped

  cadvisor:
    <<: *shared
    image: gcr.io/cadvisor/cadvisor:latest
    privileged: true
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro

  portainer:
    <<: *shared
    image: portainer/portainer-ce:latest
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - portainer-storage:/data

volumes:
  grafana-storage:
  prom-storage:
  portainer-storage:
  redis-storage:
