services:
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    volumes:
      -  grafana-storage:/var/lib/grafana

  prometheus:
    image: prom/prometheus
    command:
      - '--config.file=/etc/prometheus/config.yaml'
    ports:
      - 9090:9090
    volumes:
      - ./prometheus:/etc/prometheus
      - prom-storage:/prometheus
    depends_on:
      - cadvisor
    restart: unless-stopped

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    privileged: true
    ports:
      - 88:8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: redis:latest
    volumes:
      - redis-storage:/data
    restart: unless-stopped

  portainer:
    image: portainer/portainer-ce:latest
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - portainer-storage:/data
    restart: unless-stopped

volumes:
  grafana-storage:
  prom-storage:
  portainer-storage:
  redis-storage:
